---
name: criticism
version: 1.02
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
abstract: Perl pragma to enforce coding standards and best-practices.
license: perl
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  Repository: http://perlcritic.tigris.org/svn/perlcritic/trunk/criticism/
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
requires:
  Perl::Critic: 1.089
build_requires:
  IO::String: 0
  Test::More: 0
dynamic_config: 1
provides:
  criticism:
    file: lib/criticism.pm
    version: 1.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
