---
name: criticism
version: 1.01
author:
  - Jeffrey Thalhammer <thaljef@cpan.org>
abstract: Perl pragma to enforce coding standards and best-practices
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Perl::Critic: 0.21
build_requires:
  Test::More: 0
provides:
  criticism:
    file: lib/criticism.pm
    version: 1.01
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
