---
name: criticism
version: 0.04
author:
  - Jeffrey Thalhammer <thaljef@cpan.org>
abstract: Perl pragma to enforce coding standards and best-practices
license: perl
requires:
  Perl::Critic: 0.21
build_requires:
  Test::More: 0
provides:
  criticism:
    file: lib/criticism.pm
    version: 0.04
generated_by: Module::Build version 0.2611
