# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         criticism
version:      0.01
version_from: lib/criticism.pm
installdirs:  site
requires:
    Perl::Critic:                  0.1301

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
